apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: springboot
  name: spring-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springboot
    spec:
      imagePullSecrets:
      - name: dockerreposecret
      containers:
      - image: 172.31.43.54:8083/spring-boot-mongo
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080  
